### ISSUE TITLE
C-sources does not include file globbing.

### ISSUE THREAD

**Issue by georgewsinger** [sol/hpack#145] opened 2017-01-11 12:41 UTC

**Comment by yamadapc** [comment] 2017-01-11 17:21
Interestingly a duplicate of #118. Should have been fixed by #123.

**Comment by georgewsinger** [comment] 2017-01-11 20:53
Stack had an old version of hpack on my system. Updating to the newest version fixed this issue.

**Comment by sol** [comment] 2017-01-12 01:29
I released this to Hackage yesterday.

Closing, please reopen if there is still an issue.

**Closed by sol** 2017-01-12 01:29 UTC
