### ISSUE TITLE
Multiple executables become codependent on each other's main modules in cabal file.

### ISSUE THREAD

**Issue by semenov-vladyslav** [sol/hpack#344] opened 2018-12-06 22:47 UTC
I use `stack` version 1.9.1. Here is `package.yaml`:
```
name:                t
version:             0.1.0.0
dependencies:
- base >= 4.7 && < 5
executables:
  A:
    main:                A.hs
    source-dirs:         app
  B:
    main:                B.hs
    source-dirs:         app
```
The `app` dir contains `A.hs` and `B.hs` with the same content:
```
module Main where
main = return ()
```
The output `t.cabal` file:
```
cabal-version: 1.12

-- This file has been generated from package.yaml by hpack version 0.31.0.
--
-- see: https://github.com/sol/hpack
--
-- hash: 1008633b713715eec12fdd76aea9fbc74a167997a7131830f9cd0e3f77f373f6

name:           t
version:        0.1.0.0
license:        BSD3
license-file:   LICENSE
build-type:     Simple

executable A
  main-is: A.hs
  other-modules:
      B
      Paths_t
  hs-source-dirs:
      app
  build-depends:
      base >=4.7 && <5
  default-language: Haskell2010

executable B
  main-is: B.hs
  other-modules:
      A
      Paths_t
  hs-source-dirs:
      app
  build-depends:
      base >=4.7 && <5
  default-language: Haskell2010
```

Note the `other-modules`: executables become codependent and `ghc` fails which is not expected behaviour. If I manually remove redundant dependencies in `t.cabal` (`A` and `B` from `other-modules`) everything works fine.

Is it perhaps an issue with `stack` (like it should pass additional options to `hpack`)?

**Comment by sol** [comment] 2018-12-30 11:51
I think this is a duplicate of https://github.com/sol/hpack/issues/188.

Workaround: Put your main modules in a separate driver (e.g. `driver`) or specify other-modules explicitly.

We still want to address this in `hpack` I guess.  But having driver modules in a separate directory may be a cleaner option in some cases independently from what `hpack` does here.

**Closed** 2020-11-10 13:54 UTC
Labels: duplicate
