### ISSUE TITLE
Paths_foo in other modules

### ISSUE THREAD

**Issue by dschrempf** [sol/hpack#384] opened 2020-04-22 13:41 UTC
Cabal complains about `Paths_foo` being added to other modules. I didn't have that before. Do you know what has changed in the meantime?

```
unexpected Sublibrary dependency syntax used. To use this syntax the package needs to specify at least 'cabal-version: 3.0'. Alternatively, if you are depending on an internal library, you can write directly the library name as it were a package.
expecting space
```

If I use verbatim cabal version 3.0, cabal does not understand the license field, as already reported in #383.

**Comment by vaclavsvejcar** [comment] 2020-04-23 21:13
Have the same issue, wasn't sure if this is _hpack_ or _stack_ related issue.

**Comment by dschrempf** [comment] 2020-04-27 06:24
Update: I can create the source tarball with stack when using the following configuration options in the `package.yaml` file:
```
license:             GPL-3.0-or-later
verbatim:
  cabal-version: 3.0
library:
  source-dirs: src
  generated-other-modules: Paths_foo
```
However, I still think this is a bug in `hpack`, because manual intervention of this scale should not be required.

**Comment by sol** [comment] 2020-05-03 04:42
@dschrempf thanks for reporting this.

Please provide a minimal example that reproduces your issue.  That will help a lot! Thanks!

**Comment by dschrempf** [comment] 2020-05-04 10:40
It is not yet a minimal example, but it is somewhat small.

`package.yaml`
```
name:                test
version:             0.0.1
license:             GPL-3.0-or-later
license-file:        LICENSE
author:              "Jagger"
maintainer:          "acdc@trust.db"
copyright:           "Wild Cat (2020)"

# Metadata used when publishing your package
synopsis:            Great stuff is happening here
category:            GitHub issues

description:
  A nice description.

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - base
```

Created `test.cabal`
```
cabal-version: 2.2

-- This file has been generated from package.yaml by hpack version 0.33.0.
--
-- see: https://github.com/sol/hpack
--
-- hash: 547d141643e3bd9828eeeb880a6190d755984d78d3b2c18c1ad91f0ab1723da1

name:           test
version:        0.0.1
synopsis:       Great stuff is happening here
description:    A nice description.
category:       GitHub issues
author:         Jagger
maintainer:     acdc@trust.db
copyright:      Wild Cat (2020)
license:        GPL-3.0-or-later
license-file:   LICENSE
build-type:     Simple

library
  other-modules:
      Paths_test
  hs-source-dirs:
      src
  ghc-options: -Wall
  build-depends:
      base
  default-language: Haskell2010
```

**Comment by sol** [comment] 2020-06-02 11:10
> Cabal complains about `Paths_foo` being added to other modules.
So this is the issue that we are talking about.

@dschrempf I can't figure out how that example reproduces the issue.  Am I missing something?

**Comment by dschrempf** [comment] 2020-06-02 17:12
The created cabal file includes Paths_test in other modules, and the error in the first post is reported when compile the project.

**Comment by sol** [comment] 2020-06-03 00:11
Can't reproduce, closing.

If somebody can provide detailed steps on how to reproduce, then please open a new issue.

**Closed by sol** 2020-06-03 00:11 UTC
Labels: info needed, invalid

**Comment by sol** [comment] 2020-06-03 00:40
```
unexpected Sublibrary dependency syntax used. To use this syntax the package needs to specify at least 'cabal-version: 3.0'. Alternatively, if you are depending on an internal library, you can write directly the library name as it were a package.
expecting space
```
@dschrempf proper support for `lib:sublib` dependency syntax has been added in `hpack-0.34.2`.  This should resolve this issue.


As for `Paths_*`, as soon as the generated cabal file requires `cabal-version: 2.0` (or later), `cabal sdist` will complain.

Workaround, as you already found out, add the following to e.g. the `library`-stanza:

```
  generated-other-modules: Paths_<package>
```

This is not ideal.  The fact that `hpack` adds `Paths_*` to `other-modules` has led to friction in the past.  In retrospect, this was not a good idea in the first place.  The reason that I haven't changed it yet is that it's a breaking change with no clear upgrade path.

**Comment by dschrempf** [comment] 2020-06-03 07:56
Thanks! Sorry, I did not know that!

On June 3, 2020 2:41:06 AM GMT+02:00, Simon Hengel <notifications@github.com> wrote:
>```
>unexpected Sublibrary dependency syntax used. To use this syntax the
>package needs to specify at least 'cabal-version: 3.0'. Alternatively,
>if you are depending on an internal library, you can write directly the
>library name as it were a package.
>expecting space
>```
>@dschrempf proper support for `lib:sublib` dependency syntax has been
>added in `hpack-0.34.2`.  This should resolve this issue.
>
>
>As for `Paths_*`, as soon as the generated cabal file requires
>`cabal-version: 2.0` (or later), `cabal sdist` will complain.
>
>Workaround, as you already found out, add the following to e.g. the
>`library`-stanza:
>
>```
>  generated-other-modules: Paths_<package>
>```
>
>This is not ideal.  The fact that `hpack` adds `Paths_*` to
>`other-modules` has led to friction in the past.  In retrospect, this
>was not a good idea in the first place.  The reason that I haven't
>changed it yet is that it's a breaking change with no clear upgrade
>path.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sol/hpack/issues/384#issuecomment-637887644

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dschrempf** [comment] 2020-06-08 20:46
Sorry to bother you but I am still hitting this. Every time I publish with `stack`, I have to add

```
verbatim:
  cabal-version: 3.0
library:
  generated-other-modules: Paths_foo
```

to my `package.yaml` files.

**Comment by sol** [comment] 2020-06-09 05:55
@dschrempf please check the output of `stack --version`.

**Comment by dschrempf** [comment] 2020-06-11 11:40
So it turns out, that the error

    unexpected Sublibrary dependency syntax used. To use this syntax the package needs to specify at least 'cabal-version: 3.0'. Alternatively, if you are depending on an internal library, you can write directly the library name as it were a package.
    expecting space

is caused by a regression in Stack, which fails handling PVP boundaries after an update of Cabal (see https://github.com/commercialhaskell/stack/issues/5289). I am sorry for bothering you with this error, but it seemed that it was related to the `generated-other-modules` issue, which is still bugging me.

My Stack version is:

    Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (dirty) (8103 commits) x86_64
    Compiled with:
    - Cabal-3.2.0.0
    - Glob-0.10.0
    - StateVar-1.2
    - aeson-1.5.1.0
    - annotated-wl-pprint-0.7.0
    - ansi-terminal-0.10.3
    - ansi-wl-pprint-0.6.9
    - array-0.5.4.0
    - asn1-encoding-0.9.6
    - asn1-parse-0.9.5
    - asn1-types-0.3.4
    - assoc-1.0.1
    - async-2.2.2
    - attoparsec-0.13.2.4
    - attoparsec-iso8601-1.0.1.0
    - auto-update-0.1.6
    - base-4.14.0.0
    - base-compat-0.11.1
    - base-compat-batteries-0.11.1
    - base-orphans-0.8.2
    - base16-bytestring-0.1.1.6
    - base64-bytestring-1.1.0.0
    - basement-0.0.11
    - bifunctors-5.5.7
    - binary-0.8.8.0
    - bitarray-0.0.1.1
    - blaze-builder-0.4.1.0
    - blaze-html-0.9.1.2
    - blaze-markup-0.8.2.5
    - bytestring-0.10.10.0
    - casa-client-0.0.1
    - casa-types-0.0.1
    - case-insensitive-1.2.1.0
    - cereal-0.5.8.1
    - clock-0.8
    - colour-2.3.5
    - comonad-5.0.6
    - conduit-1.3.2
    - conduit-extra-1.3.5
    - connection-0.3.1
    - constraints-0.12
    - containers-0.6.2.1
    - contravariant-1.5.2
    - cookie-0.4.5
    - cryptohash-sha256-0.11.101.0
    - cryptonite-0.26
    - cryptonite-conduit-0.2.2
    - data-default-class-0.1.2.0
    - deepseq-1.4.4.0
    - digest-0.0.1.2
    - directory-1.3.6.0
    - distributive-0.6.2
    - dlist-0.8.0.8
    - easy-file-0.2.2
    - echo-0.1.3
    - ed25519-0.0.5.0
    - either-5.0.1.1
    - enclosed-exceptions-1.0.3
    - exceptions-0.10.4
    - extra-1.7.3
    - fast-logger-3.0.1
    - file-embed-0.0.12.0
    - filelock-0.1.1.4
    - filepath-1.4.2.1
    - fsnotify-0.3.0.1
    - generic-deriving-1.13.1
    - ghc-boot-th-8.10.1
    - ghc-prim-0.6.1
    - githash-0.1.4.0
    - hackage-security-0.6.0.1
    - hashable-1.3.0.0
    - hi-file-parser-0.1.0.0
    - hinotify-0.4
    - hourglass-0.2.12
    - hpack-0.34.2
    - hpc-0.6.1.0
    - http-api-data-0.4.1.1
    - http-client-0.7.0
    - http-client-tls-0.3.5.3
    - http-conduit-2.3.7.3
    - http-download-0.2.0.0
    - http-types-0.12.3
    - infer-license-0.2.0
    - integer-gmp-1.0.3.0
    - integer-logarithms-1.0.3
    - libyaml-0.1.2
    - lifted-async-0.10.0.6
    - lifted-base-0.2.3.12
    - lukko-0.1.1.2
    - megaparsec-8.0.0
    - memory-0.15.0
    - microlens-0.4.11.2
    - microlens-mtl-0.2.0.1
    - microlens-th-0.4.3.5
    - mime-types-0.1.0.9
    - mintty-0.1.2
    - monad-control-1.0.2.3
    - monad-logger-0.3.32
    - monad-loops-0.4.3
    - mono-traversable-1.0.15.1
    - mtl-2.2.2
    - mustache-2.3.1
    - neat-interpolation-0.5.1
    - network-3.1.1.1
    - network-uri-2.6.3.0
    - old-locale-1.0.0.7
    - old-time-1.1.0.3
    - open-browser-0.2.1.0
    - optparse-applicative-0.15.1.0
    - optparse-simple-0.1.1.2
    - pantry-0.4.0.1
    - parsec-3.1.14.0
    - parser-combinators-1.2.1
    - path-0.8.0
    - path-io-1.6.0
    - path-pieces-0.2.1
    - pem-0.2.4
    - persistent-2.10.5.2
    - persistent-sqlite-2.10.6.2
    - persistent-template-2.8.2.3
    - pretty-1.1.3.6
    - primitive-0.7.0.1
    - process-1.6.8.2
    - profunctors-5.5.2
    - project-template-0.2.0.1
    - random-1.1
    - regex-applicative-0.3.3.1
    - regex-applicative-text-0.1.0.1
    - resource-pool-0.2.3.2
    - resourcet-1.2.4.1
    - retry-0.8.1.2
    - rio-0.1.16.0
    - rio-orphans-0.1.1.0
    - rio-prettyprint-0.1.0.0
    - rts-1.0
    - safe-0.3.19
    - safe-exceptions-0.1.7.0
    - scientific-0.3.6.2
    - semigroupoids-5.3.4
    - shelly-1.8.1
    - silently-1.2.5.1
    - socks-0.6.1
    - split-0.2.3.4
    - stm-2.5.0.0
    - stm-chans-3.0.0.4
    - streaming-commons-0.2.1.2
    - syb-0.7.1
    - system-fileio-0.3.16.4
    - system-filepath-0.4.14
    - tagged-0.8.6
    - tar-0.5.1.1
    - tar-conduit-0.3.2
    - template-haskell-2.16.0.0
    - temporary-1.3
    - text-1.2.3.2
    - text-metrics-0.3.0
    - th-abstraction-0.3.2.0
    - th-expand-syns-0.4.6.0
    - th-lift-0.8.1
    - th-lift-instances-0.1.17
    - th-reify-many-0.1.9
    - these-1.1
    - time-1.9.3
    - time-compat-1.9.3
    - tls-1.5.4
    - transformers-0.5.6.2
    - transformers-base-0.4.5.2
    - transformers-compat-0.6.5
    - type-equality-1
    - typed-process-0.2.6.0
    - unicode-transforms-0.3.6
    - unix-2.7.2.2
    - unix-compat-0.5.2
    - unix-time-0.4.7
    - unliftio-0.2.13
    - unliftio-core-0.2.0.1
    - unordered-containers-0.2.10.0
    - uuid-types-1.0.3
    - vector-0.12.1.2
    - vector-algorithms-0.8.0.3
    - x509-1.7.5
    - x509-store-1.6.7
    - x509-system-1.6.6
    - x509-validation-1.6.11
    - yaml-0.11.4.0
    - zip-archive-0.4.1
    - zlib-0.6.2.1

    Warning: this is an unsupported build that may use different versions of
    dependencies and GHC than the officially released binaries, and therefore may
    not behave identically.  If you encounter problems, please try the latest
    official build by running 'stack upgrade --force-download'.
